server:
  port: 8085

spring:
  application:
    name: CART-SERVICE

  datasource:
    url: jdbc:postgresql://postgres:5432/cart_db
    username: postgres
    password: Bunny@120

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discoveryserver:8761/eureka/
