name: Backend CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Discovery Server
        run: |
          cd discoveryserver
          mvn clean install -DskipTests

      - name: Build API Gateway
        run: |
          cd apigateway
          mvn clean install -DskipTests

      - name: Build User Service
        run: |
          cd userservice
          mvn clean install -DskipTests

      - name: Build Order Service
        run: |
          cd orderservice
          mvn clean install -DskipTests

      - name: Build Product Service
        run: |
          cd productservice
          mvn clean install -DskipTests
